package moneycalculator.model;

import java.util.HashMap;
import java.util.Map;

public class CurrencyList {

    private final Map<String, Currency> currencies = new HashMap<>();

    public CurrencyList() {
        add(new Currency("AED", "Dírham", "د.إ"));
        add(new Currency("AFN", "Afgani", "؋"));
        add(new Currency("ALL", "Lek", "L"));
        add(new Currency("AMD", "Dram armenio", ""));
        add(new Currency("ANG", "Florín de las Antillas Neerlandesas", "ƒ"));
        add(new Currency("AOA", "Kuanza de Angola", "Kz"));
        add(new Currency("ARS", "Peso argentino", "$"));
        add(new Currency("AUD", "Dólar australiano", "$"));
        add(new Currency("AWG", "Florín arubano", "ƒ"));
        add(new Currency("AZN", "Manat azerbayano", ""));
        add(new Currency("BAM", "Marco convertible de Bosnia y Herzegovina", "KM"));
        add(new Currency("BBD", "Dólar de las Barbados", "$"));
        add(new Currency("BDT", "Taka de Bangladés", "৳"));
        add(new Currency("BGN", "Leva búlgaro", "лв"));
        add(new Currency("BHD", "Dinar de Baréin", ".د.ب"));
        add(new Currency("BIF", "Franco burundés", "Fr"));
        add(new Currency("BND", "Dólar de Brunei", "$"));
        add(new Currency("BOB", "Boliviano", "Bs."));
        add(new Currency("BRL", "Real brasileño", "R$"));
        add(new Currency("BSD", "Dólar de las Bahamas", "$"));
        add(new Currency("BTN", "Gultrum butanés", "Nu."));
        add(new Currency("BWP", "Pula de Botsuana", "P"));
        add(new Currency("BYR", "Rublo bielorruso", "Br"));
        add(new Currency("BZD", "Dólar beliceño", "$"));
        add(new Currency("CAD", "Dólar canadiense", "$"));
        add(new Currency("CDF", "Franco congoleño", "Fr"));
        add(new Currency("CHF", "Franco suizo", "Fr"));
        add(new Currency("CLP", "Peso chileno", "$"));
        add(new Currency("CNY", "Yuan, renminbi", "¥, 元"));
        add(new Currency("COP", "Peso colombiano", "$"));
        add(new Currency("CRC", "Colón costarricense", "₡"));
        add(new Currency("CUP", "Peso cubano", "$"));
        add(new Currency("CVE", "Escudo de Cabo Verde", "Esc, $"));
        add(new Currency("CZK", "Corona checa", "Kč"));
        add(new Currency("DJF", "Franco yibutiano", "Fr"));
        add(new Currency("DKK", "Corona danesa", "kr"));
        add(new Currency("DOP", "Peso dominicano", "$"));
        add(new Currency("DZD", "Dinar", "د.ج"));
        add(new Currency("EGP", "Libra egipcia", "£, ج.م"));
        add(new Currency("ERN", "Nakfa de Eritrea", "Nfk"));
        add(new Currency("ETB", "Bir", "Br"));
        add(new Currency("EUR", "Euro", "€"));
        add(new Currency("GBP", "Libra esterlina", "£"));
        add(new Currency("GEL", "Lari georgiano", "ლ"));
        add(new Currency("GHS", "Cedi de Gana", "₵"));
        add(new Currency("GIP", "Libra de Gibraltar", "£"));
        add(new Currency("GMD", "Dalasi gambiano", "D"));
        add(new Currency("GNF", "Franco guineano", "Fr"));
        add(new Currency("GTQ", "Quetzal", "Q"));
        add(new Currency("HNL", "Lempira", "L"));
        add(new Currency("HRK", "Kuna croata", "kn"));
        add(new Currency("HTG", "Gurde", "G"));
        add(new Currency("HUF", "Forinto", "Ft"));
        add(new Currency("IDR", "Rupia indonesia", "Rp"));
        add(new Currency("ILS", "Nuevo séquel", "₪"));
        add(new Currency("INR", "Rupia india", "₹"));
        add(new Currency("IQD", "Dinar irakí", "ع.د"));
        add(new Currency("IRR", "Rial iraní", "﷼"));
        add(new Currency("ISK", "Corona islandesa", "kr"));
        add(new Currency("JMD", "Dólar jamaicano", "$"));
        add(new Currency("JOD", "Dinar jordano", "د.ا"));
        add(new Currency("JPY", "Yen", "¥"));
        add(new Currency("KES", "Chelín keniano", "Sh"));
        add(new Currency("KGS", "Som kirguís", "лв"));
        add(new Currency("KHR", "Riel camboyano", "៛"));
        add(new Currency("KMF", "Franco comorano", "Fr"));
        add(new Currency("KPW", "Won norcoreano", "₩"));
        add(new Currency("KRW", "Won surcoreano", "₩"));
        add(new Currency("KWD", "Dinar kuwaití", "د.ك"));
        add(new Currency("KYD", "Dólar de las Islas Caimán", "$"));
        add(new Currency("KZT", "Tengue kazajo", "₸"));
        add(new Currency("LAK", "Kip", "₭"));
        add(new Currency("LBP", "Libra libanesa", "ل.ل"));
        add(new Currency("LKR", "Rupia ceilandesa", "Rs"));
        add(new Currency("LRD", "Dólar liberiano", "$"));
        add(new Currency("LSL", "Loti de Lesoto", "L"));
        add(new Currency("LTL", "Litas", "Lt"));
        add(new Currency("LVL", "Lats", "Ls"));
        add(new Currency("LYD", "Dinar libio", "ل.د"));
        add(new Currency("MAD", "Dírham", "د.م."));
        add(new Currency("MDL", "Leu moldavo", "L"));
        add(new Currency("MGA", "Ariari", "Ar"));
        add(new Currency("MKD", "Denar", "ден"));
        add(new Currency("MMK", "Kiat de Birmania", "K"));
        add(new Currency("MNT", "Tugrik mongol", "₮"));
        add(new Currency("MOP", "Pataca de Macao", "P"));
        add(new Currency("MRO", "Uguiya", "UM"));
        add(new Currency("MUR", "Rupia de Mauricio", "₨"));
        add(new Currency("MVR", "Rufiya", ".ރ"));
        add(new Currency("MWK", "Kuacha de Malaui", "MK"));
        add(new Currency("MXN", "Peso mexicano", "$"));
        add(new Currency("MYR", "Ringit", "RM"));
        add(new Currency("MZN", "Metical", "MT"));
        add(new Currency("NAD", "Dólar de Namibia", "$"));
        add(new Currency("nenhum", "Dólar micronesio", "$"));
        add(new Currency("Nenhum", "Dólar nauruano", "$"));
        add(new Currency("NGN", "Naira nigeriano", "₦"));
        add(new Currency("NIO", "Córdoba nicaragüense", "C$"));
        add(new Currency("NOK", "Corona noruega", "kr"));
        add(new Currency("NPR", "Rupia nepalí", "₨"));
        add(new Currency("NZD", "Dólar de Nueva Zelanda", "$"));
        add(new Currency("OMR", "Rial de Omán", "ر.ع."));
        add(new Currency("PAB", "Balboa panameño", "B/."));
        add(new Currency("PEN", "Nuevo sol peruano", "S/."));
        add(new Currency("PGK", "Kina", "K"));
        add(new Currency("PHP", "Peso filipino", "₱"));
        add(new Currency("PKR", "Rupia pakistaní", "₨"));
        add(new Currency("PLN", "Złóti", "zł"));
        add(new Currency("PYG", "Guaraní paraguayo", "₲"));
        add(new Currency("QAR", "Rial catarí", "ر.ق"));
        add(new Currency("RON", "Leu rumano", "L"));
        add(new Currency("RSD", "Dinar serbio", "дин.,din."));
        add(new Currency("RUB", "Rublo", "₽"));
        add(new Currency("RWF", "Franco ruandés", "Fr"));
        add(new Currency("SAR", "Rial saudí", "ر.س"));
        add(new Currency("SBD", "Dólar salomonense", "$"));
        add(new Currency("SCR", "Rupia seychellense", "₨"));
        add(new Currency("SDG", "Libra sudanesa", "£"));
        add(new Currency("SEK", "Corona sueca", "kr"));
        add(new Currency("SGD", "Dólar singapurense", "$"));
        add(new Currency("SLL", "Leona", "Le"));
        add(new Currency("SOS", "Chelín somalí", "Sh"));
        add(new Currency("SRD", "Dólar surinamés", "$"));
        add(new Currency("SSP", "Libra sursudanesa", "£"));
        add(new Currency("STD", "Dobra", "Db"));
        add(new Currency("SVC", "Colón salvadoreño", "₡"));
        add(new Currency("SYP", "Libra siria", "£,ل.س"));
        add(new Currency("SZL", "Lilangeni", "L"));
        add(new Currency("THB", "Bat", "฿"));
        add(new Currency("TJS", "Somoni", "ЅМ"));
        add(new Currency("TMT", "Manat turcomano", "m"));
        add(new Currency("TND", "Dinar tunecino", "د.ت"));
        add(new Currency("TOP", "Paanga", "T$"));
        add(new Currency("TRY", "Lira turca", ""));
        add(new Currency("TTD", "Dólar trinitense", "$"));
        add(new Currency("TWD", "Nuevo dólar de Taiwán", "$"));
        add(new Currency("TZS", "Chelín tanzaniano", "Sh"));
        add(new Currency("UAH", "Grivna", "₴"));
        add(new Currency("UGX", "Chelín ugandés", "Sh"));
        add(new Currency("USD", "Dólar estadounidense", "$"));
        add(new Currency("UYU", "Peso uruguayo", "$"));
        add(new Currency("UZS", "Sum", "лв"));
        add(new Currency("VEF", "Bolívar fuerte", "Bs F"));
        add(new Currency("VND", "Dong", "₫"));
        add(new Currency("VUV", "Vatu do Vanuatu", "Vt"));
        add(new Currency("WST", "Tala", "T"));
        add(new Currency("XAF", "Franco CFA", "Fr"));
        add(new Currency("XAF", "Franco CFA", "Fr"));
        add(new Currency("XCD", "Dólar del Caribe Oriental", "$"));
        add(new Currency("XOF", "Franco CFA", "Fr"));
        add(new Currency("XPF", "Franco CFP", "Fr"));
        add(new Currency("YER", "Rial yemení", "﷼"));
        add(new Currency("ZAR", "Rand", "R"));
        add(new Currency("ZMK", "Kuacha zambiano", "ZK"));
        add(new Currency("ZWL", "Dólar zimbabuense", "$"));
    }

    private void add(Currency currency) {
        currencies.put(currency.getCode(), currency);
    }

    public Currency get(String code) {
        return currencies.get(code.toUpperCase());
    }
}
